server:
  port: 8092    
spring:     #定义springmvc视图解析器
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
dubbo:
  scan:
    basePackages: com.jt   #dubbo的包扫描
  application:
    name: consumer-user     #服务名称
  registry:
    address: zookeeper://192.168.234.134:2181?backup=192.168.234.134:2182,192.168.234.134:2183

  