//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : pd
//  @ File Name : SearchController.java
//  @ Date : 2019/5/15
//  @ Author : 
//
//



package com.tude.controller;


public class SearchController {
	public com.tude.service.SearchService searchService;
	public String search(String key, String username) {
	
	}
}
