//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : pd
//  @ File Name : SearchService.java
//  @ Date : 2019/5/15
//  @ Author : 
//
//



package com.tude.service;


public class SearchService {
}
